### ISSUE TITLE
SyntaxError: Unexpected reserved word await

### ISSUE THREAD

**Issue by gronostajo** [OzzyCzech/pux-to-html#1]
Hi! I've just installed this in Ubuntu 22.04 in WSL.

```
apt update
apt install -y nodejs npm 
npm install -g pux-to-html
pux2html foo.1pux bar
```

I'm getting an error:

```
file:///usr/local/lib/node_modules/pux-to-html/index.js:20
    await puxToHtml(input, output);
    ^^^^^

SyntaxError: Unexpected reserved word
(…)
```

Ubuntu version is 22.04, it has installed node.js v12.22.9 and npm 8.5.1 from Ubuntu repos.

**Comment by OzzyCzech** [comment]
Hi @gronostajo 

nodejs version 12 is way to old. Current version is v22, you should upgrade at last to **Node version v20** then `await` should work as usual

**Comment by gronostajo** [comment]
Hello, thanks for a quick response.

I gave it a try on Ubuntu 24.04 which ships with node.js v18.19.1 and it worked, so your recommendation was accurate and helpful, I appreciate it.

Ubuntu 22.04 is still a very popular distribution that will be supported until April 2027, so making the tool compatible with the version of Node that it ships would be a welcome improvement I think. That being said I realize that this is an effort that may not pay off.

**Comment by OzzyCzech** [comment]
I'm glad to hear that it was helpful. You can install any version of the Nodejs to the older Ubuntu versions:

Remove Nodejs version from official repository

```shell
sudo apt remove nodejs
sudo apt autoremove
```

then set

```
curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
sudo apt-get install -y nodejs
node -v
```

You can try change version to the `https://deb.nodesource.com/setup_21.x` or `https://deb.nodesource.com/setup_22.x`

Another option is use [Node Version Manager](https://github.com/nvm-sh/nvm)

```shell
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
source ~/.nvm/nvm.sh
```
then just

```shell
nvm install 20
```
